apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cloudformation-operator.name" . }}
  labels:
{{ include "cloudformation-operator.helmStandardLabels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: {{ template "cloudformation-operator.name" . }}
  template:
    metadata:
      annotations:
        {{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
        {{- end }}
      labels:
        name: {{ template "cloudformation-operator.name" . }}
{{ include "cloudformation-operator.helmPodLabels" . | indent 8 }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{ end }}
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "cloudformation-operator.name" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
      containers:
        - name: cloudformation-operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
          - cloudformation-operator
          args:
{{- if .Values.operator.region }}
          - --region={{ .Values.operator.region }}
        {{- end }}
{{- if .Values.tags }}
{{- range $key, $value := .Values.tags }}
          - --tag={{ $key }}={{ $value }}
        {{- end }}
        {{- end }}
{{- if .Values.capability.enabled }}
          - --capability CAPABILITY_IAM
        {{- end }}
          env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: {{ template "cloudformation-operator.name" . }}
{{- if .Values.extraEnv}}
          {{- range $key, $value := .Values.extraEnv }}
          - name: {{ $key }}
            value: {{ $value }}
          {{- end }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          {{- end }}
{{- if .Values.extraVolumeMounts }}
          volumeMounts:
{{ toYaml .Values.extraVolumeMounts | indent 12 }}
{{- end }}
{{- if .Values.extraVolumes }}
      volumes:
{{ toYaml .Values.extraVolumes | indent 8 }}
{{- end }}
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
