# Default values for cloudformation-operator
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: quay.io/linki/cloudformation-operator
  tag: v0.7.0
  pullPolicy: IfNotPresent

replicas: 1

## Pod Annotations
podAnnotations:
#  iam.amazonaws.com/role: "arn:aws:iam::<ACCOUNT_ID>:role/cloudformation-operator"

## App config
operator:
  region: eu-central-1

#You may want to assign tags to your CloudFormation stacks. 
#The tags added to a CloudFormation stack will be propagated to the managed resources.
tags:
#  wambo: baz
#  foo: bar

#Enable specified capabilities for all stacks managed by the operator instance.
capability:
  enabled: false

## RBAC roles and bindings
rbac:
  create: true
  serviceAccountName: cloudformation-operator

## Pod Resources
#resources:
#  requests:
#    memory: "64Mi"
#    cpu: "250m"
#  limits:
#    memory: "128Mi"
#    cpu: "500m"

## Pod Affinity
affinity: {}

## A list of additional environment variables
extraEnv:
  #- name: my_env
  #  value: my_value

## Additional Volumes and mounts
extraVolumes:
  #- hostPath:
  #    path: /var/log
  #  name: logs
extraVolumeMounts:
  #- name: logs
  #  mountPath: /host/var/log
  #  readOnly: true

## Node Selector
nodeSelector:
  #disktype: ssd

## Pod Tolerations
tolerations:
  #- key: "node.kubernetes.io/not-ready"
  #  operator: "Exists"
  #  effect: "NoExecute"
  #  tolerationSeconds: 6000
