apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudformation-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cloudformation-operator
  template:
    metadata:
      labels:
        name: cloudformation-operator
    spec:
      serviceAccountName: cloudformation-operator
      containers:
        - name: cloudformation-operator
          image: quay.io/linki/cloudformation-operator:v0.7.0
          command:
          - cloudformation-operator
          args:
          - --region=eu-central-1
          env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: cloudformation-operator
